### ISSUE TITLE
P2P sync performance improvements - incorrect authorization details provided

### ISSUE THREAD

**Issue by muchuri** [OpenSRP/opensrp-client-chw#1742] opened 2021-03-18 19:52 UTC
The client has reported an issue with P2P sync performance improvements on different CHSS-CHA accounts unsuccessfully. The application responds with an error message is "incorrect authorization details provided"

**Comment by cafootitt** [comment] 2021-03-22 08:51
Blocked, as we're unable to reproduce on testing accounts; waiting for the client to share the affected accounts.

**Comment by cafootitt** [comment] 2021-03-30 08:32
Client is no longer reporting this, closing and moving to done column.

**Closed by cafootitt** 2021-03-30 08:32 UTC
Labels: All WCARO flavors, Togo, blocked
